package earth.worldwind.render.image

import android.graphics.Bitmap
import android.graphics.Color.argb
import androidx.annotation.DrawableRes
import dev.icerock.moko.resources.ImageResource
import earth.worldwind.util.AbstractSource
import earth.worldwind.util.DownloadPostprocessor
import earth.worldwind.util.Logger.ERROR
import earth.worldwind.util.Logger.logMessage
import java.io.File
import java.net.MalformedURLException
import java.net.URL

/**
 * Provides a mechanism for specifying images from a variety of sources. ImageSource retains the image source on behalf
 * of the caller, making this information available to WorldWind components that load images on the caller's behalf.
 * <br>
 * ImageSource supports following source types:
 * - Uniform Resource Locator [URL]
 * - Local image [File]
 * - Android [Bitmap]
 * - WorldWind [ImageSource.BitmapFactory]
 * - Android resource identifier
 * - Multi-platform resource identifier
 * <br>
 * ImageSource instances are intended to be used as a key into a cache or other data structure that enables sharing of
 * loaded images. Android bitmaps and WorldWind bitmap factories are compared by reference. Android resource identifiers
 * with equivalent IDs are considered equivalent. File paths and URLs with the same string representation considered equals.
 */
actual open class ImageSource protected constructor(source: Any): AbstractSource<Bitmap>(source) {
    actual companion object {
        protected val lineStippleFactories = mutableMapOf<Any, BitmapFactory>()

        /**
         * Constructs an image source with a multi-platform resource identifier.
         *
         * @param imageResource the multi-platform resource identifier
         *
         * @return the new image source
         */
        @JvmStatic
        actual fun fromResource(imageResource: ImageResource) = ImageSource(imageResource)

        /**
         * Constructs an image source with an Android resource identifier. The resource must be accessible from the Android
         * Context associated with the WorldWindow.
         *
         * @param id the resource identifier, as generated by the aapt tool
         *
         * @return the new image source
         */
        @JvmStatic
        fun fromResource(@DrawableRes id: Int) = ImageSource(id)

        /**
         * Constructs an image source with a [Bitmap].
         *
         * @param bitmap the [Bitmap] to use as an image source
         *
         * @return the new image source
         */
        @JvmStatic
        fun fromBitmap(bitmap: Bitmap): ImageSource {
            require(!bitmap.isRecycled) {
                logMessage(ERROR, "ImageSource", "fromBitmap", "invalidBitmap")
            }
            return ImageSource(bitmap)
        }

        /**
         * Constructs an image source with a [BitmapFactory]. WorldWind shapes configured with a bitmap factory image source
         * construct their bitmaps lazily, typically when the shape becomes visible on screen.
         *
         * @param factory the [BitmapFactory] to use as an image source
         *
         * @return the new image source
         */
        @JvmStatic
        fun fromBitmapFactory(factory: BitmapFactory) = ImageSource(factory)

        /**
         * Constructs a bitmap image source with a line stipple pattern. The result is a one-dimensional bitmap with pixels
         * representing the specified stipple factor and stipple pattern. Line stipple images can be used for displaying
         * dashed shape outlines. See [earth.worldwind.shape.ShapeAttributes.outlineImageSource].
         *
         * @param factor  specifies the number of times each bit in the pattern is repeated before the next bit is used. For
         * example, if the factor is 3, each bit is repeated three times before using the next bit. The
         * specified factor must be either 0 or an integer greater than 0. A factor of 0 indicates no
         * stippling.
         * @param pattern specifies a number whose lower 16 bits define a pattern of which pixels in the image are white and
         * which are transparent. Each bit corresponds to a pixel, and the pattern repeats after every n*16
         * pixels, where n is the factor. For example, if the factor is 3, each bit in the pattern is
         * repeated three times before using the next bit.
         *
         * @return the new image source
         */
        @JvmStatic
        actual fun fromLineStipple(factor: Int, pattern: Short): ImageSource {
            val lFactor = factor.toLong() and 0xFFFFFFFFL
            val lPattern = pattern.toLong() and 0xFFFFL
            val key = lFactor shl 32 or lPattern
            val factory = lineStippleFactories[key] ?: LineStippleBitmapFactory(factor, pattern).also {
                lineStippleFactories[key] = it
            }
            return ImageSource(factory)
        }

        /**
         * Constructs an image source with a [File].
         *
         * @param file the source [File] to use as an image source
         *
         * @return the new image source
         */
        @JvmStatic
        fun fromFile(file: File): ImageSource {
            require(file.isFile) {
                logMessage(ERROR, "ImageSource", "fromFile", "invalidFile")
            }
            return ImageSource(file)
        }

        /**
         * Constructs an image source with a file path.
         *
         * @param filePath complete path name to the file
         *
         * @return the new image source
         */
        @JvmStatic
        fun fromFilePath(filePath: String) = fromFile(File(filePath))

        /**
         * Constructs an image source with an [URL].
         *
         * @param url Uniform Resource Locator
         * @param postprocessor implementation of image post-processing routine
         *
         * @return the new image source
         */
        @JvmStatic @JvmOverloads
        fun fromUrl(url: URL, postprocessor: DownloadPostprocessor<Bitmap>? = null) =
            ImageSource(url).apply { this.postprocessor = postprocessor }

        /**
         * Constructs an image source with a URL string.
         *
         * @param urlString complete URL string
         * @param postprocessor implementation of image post-processing routine
         *
         * @return the new image source
         */
        @JvmStatic @JvmOverloads @Suppress("UNCHECKED_CAST")
        actual fun fromUrlString(urlString: String, postprocessor: DownloadPostprocessor<*>?) = try {
            fromUrl(URL(urlString), postprocessor as DownloadPostprocessor<Bitmap>?)
        } catch (e: MalformedURLException) {
            logMessage(ERROR, "ImageSource", "fromUrlString", "invalidUrlString", e)
            throw e
        }

        /**
         * Constructs an image source with a generic [Any] instance. The source may be any non-null object. This is
         * equivalent to calling one of ImageSource's type-specific factory methods when the source is a recognized type.
         *
         * @param source the generic source
         *
         * @return the new image source
         */
        @JvmStatic
        actual fun fromUnrecognized(source: Any) = when(source) {
            is ImageResource -> fromResource(source)
            is Int -> fromResource(source)
            is Bitmap -> fromBitmap(source)
            is BitmapFactory -> fromBitmapFactory(source)
            is File -> fromFile(source)
            is URL -> fromUrl(source)
            else -> ImageSource(source)
        }
    }

    /**
     * Indicates whether this image source is an Android or multi-platform resource.
     */
    val isResource get() = source is ImageResource || source is Int
    /**
     * Indicates whether this image source is a Bitmap.
     */
    val isBitmap get() = source is Bitmap
    /**
     * Indicates whether this image source is a bitmap factory.
     */
    val isBitmapFactory get() = source is BitmapFactory
    /**
     * Indicates whether this image source is a [File].
     */
    val isFile get() = source is File
    /**
     * Indicates whether this image source is an [URL].
     */
    val isUrl get() = source is URL

    /**
     * @return the source Android or multi-platform resource identifier.
     * Call isResource to determine whether the source is an Android or multi-platform resource.
     */
    @DrawableRes
    fun asResource() = if (source is ImageResource) source.drawableResId else source as Int

    /**
     * @return the source [Bitmap]. Call isBitmap to determine whether the source is a bitmap.
     */
    fun asBitmap() = source as Bitmap

    /**
     * @return the source [BitmapFactory]. Call isBitmapFactory to determine whether the source is a bitmap
     * factory.
     */
    fun asBitmapFactory() = source as BitmapFactory

    /**
     * @return the source [File]. Call [isFile] to determine whether the source is a [File].
     */
    fun asFile() = source as File

    /**
     * @return the source [URL]. Call [isUrl] to determine whether the source is an [URL].
     */
    fun asUrl() = source as URL

    override fun toString() = when (source) {
        is ImageResource -> "Resource: $source"
        is Int -> "Resource: $source"
        is Bitmap -> "Bitmap: $source"
        is BitmapFactory -> "BitmapFactory: $source"
        is File -> "File: $source"
        is URL -> "URL: $source"
        else -> super.toString()
    }

    /**
     * Factory for delegating construction of bitmap images. WorldWind shapes configured with a BitmapFactory construct
     * their bitmaps lazily, typically when the shape becomes visible on screen.
     */
    interface BitmapFactory {
        /**
         * Returns the bitmap associated with this factory. This method may be called more than once and may be called
         * from a non-UI thread. Each invocation must return a bitmap with equivalent content, dimensions and
         * configuration. Any side effects applied to the WorldWind scene by the factory must be executed on the main
         * thread.
         * <br>
         * The factory must not retain any reference to the returned bitmap and must not attempt to recycle the bitmap.
         *
         * @return the bitmap associated with this factory
         */
        fun createBitmap(): Bitmap?
    }

    protected open class LineStippleBitmapFactory(protected val factor: Int, protected val pattern: Short): BitmapFactory {
        override fun createBitmap(): Bitmap {
            val transparent = argb(0, 0, 0, 0)
            val white = argb(255, 255, 255, 255)
            return if (factor <= 0) {
                val width = 16
                val pixels = IntArray(width)
                pixels.fill(white)
                val bitmap = Bitmap.createBitmap(width, 1 /*height*/, Bitmap.Config.ARGB_8888)
                bitmap.setPixels(pixels, 0 /*offset*/, width /*stride*/, 0 /*x*/, 0 /*y*/, width, 1 /*height*/)
                bitmap
            } else {
                val width = factor * 16
                val pixels = IntArray(width)
                var pixel = 0
                for (bi in 0..15) {
                    val bit = pattern.toInt() and (1 shl bi)
                    val color = if (bit == 0) transparent else white
                    for (fi in 0 until factor) pixels[pixel++] = color
                }
                val bitmap = Bitmap.createBitmap(width, 1 /*height*/, Bitmap.Config.ARGB_8888)
                bitmap.setPixels(pixels, 0 /*offset*/, width /*stride*/, 0 /*x*/, 0 /*y*/, width, 1 /*height*/)
                bitmap
            }
        }

        override fun toString() = "LineStippleBitmapFactory factor=$factor, pattern=" + (pattern.toInt() and 0xFFFF).toString(16).uppercase()
    }
}