[versions]
annotation = "1.10.0"
kotlin-wrappers = "2026.5.2"
appcompat = "1.7.1"
activity-compose = "1.13.0"
compose-multiplatform = "1.10.3"
lifecycle-compose = "2.10.0"
coroutines = "1.11.0"
datetime = "0.8.0"
desugar = "2.1.5"
jogl = "2.6.0"
junit = "1.3.0"
ktor = "3.4.3"
lwjgl = "3.4.1"
material = "1.13.0"
mil-sym-android = "2.10.3"
mil-sym-java = "2.7.3"
mil-sym-ts = "2.8.3"
mockk = "1.14.9"
geopackage-core = "6.6.7"
geopackage-android = "6.7.5"
geopackage-java = "6.6.5"
ormlite = "6.1"
pngj = "2.1.0"
resources = "0.26.4"
rules = "1.7.0"
serialization = "1.11.0"
geojson = "0.6.6"
uri-kmp = "0.0.21"
vlcj = "4.12.1"
javacv = "1.5.13"
javafx = "26.0.1"
xmlutil = "0.91.3"
webp-imageio = "0.10.0"

[plugins]

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose-multiplatform" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-xml = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

moko-resources = { module = "dev.icerock.moko:resources", version.ref = "resources" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "resources" }
moko-resources-test = { module = "dev.icerock.moko:resources-test", version.ref = "resources" }

mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }

mil-sym-android = { module = "io.github.missioncommand:mil-sym-android", version.ref = "mil-sym-android" }
mil-sym-java = { module = "io.github.missioncommand:mil-sym-java", version.ref = "mil-sym-java" }

jogl = { module = "org.jogamp.jogl:jogl-all-main", version.ref = "jogl" }
gluegen = { module = "org.jogamp.gluegen:gluegen-rt-main", version.ref = "jogl" }

lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-assimp = { module = "org.lwjgl:lwjgl-assimp", version.ref = "lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }
lwjgl-openal = { module = "org.lwjgl:lwjgl-openal", version.ref = "lwjgl" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb", version.ref = "lwjgl" }

geopackage-core = { module = "mil.nga.geopackage:geopackage-core", version.ref = "geopackage-core" }
geopackage-android = { module = "mil.nga.geopackage:geopackage-android", version.ref = "geopackage-android" }
geopackage-java = { module = "mil.nga.geopackage:geopackage", version.ref = "geopackage-java" }

ormlite-core = { module = "com.j256.ormlite:ormlite-core", version.ref = "ormlite" }
ormlite-android = { module = "com.j256.ormlite:ormlite-android", version.ref = "ormlite" }
ormlite-jdbc = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite" }

desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
material = { module = "com.google.android.material:material", version.ref = "material" }
pngj = { module = "ar.com.hjg:pngj", version.ref = "pngj" }
geojson = { module = "io.data2viz.geojson:core", version.ref = "geojson" }
uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
javacv-platform = { module = "org.bytedeco:javacv-platform", version.ref = "javacv" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "javafx" }
javafx-media = { module = "org.openjfx:javafx-media", version.ref = "javafx" }
javafx-swing = { module = "org.openjfx:javafx-swing", version.ref = "javafx" }
webp-imageio = { module = "com.github.usefulness:webp-imageio", version.ref = "webp-imageio" }

kotlin-wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "kotlin-wrappers" }
kotlin-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser" }